export type Currency = { code: string; name: string; symbol: string }

export const CURRENCIES: Currency[] = [
  { code: 'USD', name: 'US Dollar',                  symbol: '$'   },
  { code: 'EUR', name: 'Euro',                        symbol: '€'   },
  { code: 'GBP', name: 'British Pound',               symbol: '£'   },
  { code: 'AUD', name: 'Australian Dollar',           symbol: 'A$'  },
  { code: 'CAD', name: 'Canadian Dollar',             symbol: 'C$'  },
  { code: 'NZD', name: 'New Zealand Dollar',          symbol: 'NZ$' },
  { code: 'CHF', name: 'Swiss Franc',                 symbol: 'Fr'  },
  { code: 'JPY', name: 'Japanese Yen',                symbol: '¥'   },
  { code: 'CNY', name: 'Chinese Yuan',                symbol: '¥'   },
  { code: 'HKD', name: 'Hong Kong Dollar',            symbol: 'HK$' },
  { code: 'SGD', name: 'Singapore Dollar',            symbol: 'S$'  },
  { code: 'INR', name: 'Indian Rupee',                symbol: '₹'   },
  { code: 'MYR', name: 'Malaysian Ringgit',           symbol: 'RM'  },
  { code: 'PHP', name: 'Philippine Peso',             symbol: '₱'   },
  { code: 'THB', name: 'Thai Baht',                   symbol: '฿'   },
  { code: 'IDR', name: 'Indonesian Rupiah',           symbol: 'Rp'  },
  { code: 'VND', name: 'Vietnamese Dong',             symbol: '₫'   },
  { code: 'KRW', name: 'South Korean Won',            symbol: '₩'   },
  { code: 'TWD', name: 'Taiwan Dollar',               symbol: 'NT$' },
  { code: 'BRL', name: 'Brazilian Real',              symbol: 'R$'  },
  { code: 'MXN', name: 'Mexican Peso',                symbol: 'Mex$'},
  { code: 'ARS', name: 'Argentine Peso',              symbol: '$'   },
  { code: 'CLP', name: 'Chilean Peso',                symbol: '$'   },
  { code: 'COP', name: 'Colombian Peso',              symbol: '$'   },
  { code: 'PEN', name: 'Peruvian Sol',                symbol: 'S/.' },
  { code: 'UYU', name: 'Uruguayan Peso',              symbol: '$U'  },
  { code: 'ZAR', name: 'South African Rand',          symbol: 'R'   },
  { code: 'NGN', name: 'Nigerian Naira',              symbol: '₦'   },
  { code: 'GHS', name: 'Ghanaian Cedi',               symbol: '₵'   },
  { code: 'KES', name: 'Kenyan Shilling',             symbol: 'KSh' },
  { code: 'TZS', name: 'Tanzanian Shilling',          symbol: 'TSh' },
  { code: 'UGX', name: 'Ugandan Shilling',            symbol: 'USh' },
  { code: 'ETB', name: 'Ethiopian Birr',              symbol: 'Br'  },
  { code: 'EGP', name: 'Egyptian Pound',              symbol: 'E£'  },
  { code: 'MAD', name: 'Moroccan Dirham',             symbol: 'د.م.'},
  { code: 'TND', name: 'Tunisian Dinar',              symbol: 'د.ت.'},
  { code: 'AED', name: 'UAE Dirham',                  symbol: 'د.إ.'},
  { code: 'SAR', name: 'Saudi Riyal',                 symbol: '﷼'   },
  { code: 'QAR', name: 'Qatari Riyal',               symbol: '﷼'   },
  { code: 'KWD', name: 'Kuwaiti Dinar',               symbol: 'د.ك.'},
  { code: 'BHD', name: 'Bahraini Dinar',              symbol: '.د.ب'},
  { code: 'OMR', name: 'Omani Rial',                  symbol: '﷼'   },
  { code: 'JOD', name: 'Jordanian Dinar',             symbol: 'JD'  },
  { code: 'ILS', name: 'Israeli Shekel',              symbol: '₪'   },
  { code: 'TRY', name: 'Turkish Lira',                symbol: '₺'   },
  { code: 'RUB', name: 'Russian Ruble',               symbol: '₽'   },
  { code: 'UAH', name: 'Ukrainian Hryvnia',           symbol: '₴'   },
  { code: 'PLN', name: 'Polish Zloty',                symbol: 'zł'  },
  { code: 'CZK', name: 'Czech Koruna',                symbol: 'Kč'  },
  { code: 'HUF', name: 'Hungarian Forint',            symbol: 'Ft'  },
  { code: 'RON', name: 'Romanian Leu',                symbol: 'lei' },
  { code: 'BGN', name: 'Bulgarian Lev',               symbol: 'лв'  },
  { code: 'HRK', name: 'Croatian Kuna',               symbol: 'kn'  },
  { code: 'RSD', name: 'Serbian Dinar',               symbol: 'din' },
  { code: 'DKK', name: 'Danish Krone',                symbol: 'kr'  },
  { code: 'SEK', name: 'Swedish Krona',               symbol: 'kr'  },
  { code: 'NOK', name: 'Norwegian Krone',             symbol: 'kr'  },
  { code: 'ISK', name: 'Icelandic Krona',             symbol: 'kr'  },
  { code: 'PKR', name: 'Pakistani Rupee',             symbol: '₨'   },
  { code: 'BDT', name: 'Bangladeshi Taka',            symbol: '৳'   },
  { code: 'LKR', name: 'Sri Lankan Rupee',            symbol: '₨'   },
  { code: 'NPR', name: 'Nepalese Rupee',              symbol: '₨'   },
  { code: 'MMK', name: 'Myanmar Kyat',                symbol: 'K'   },
  { code: 'KHR', name: 'Cambodian Riel',              symbol: '៛'   },
  { code: 'LAK', name: 'Lao Kip',                     symbol: '₭'   },
  { code: 'MNT', name: 'Mongolian Tugrik',            symbol: '₮'   },
  { code: 'AFN', name: 'Afghan Afghani',              symbol: '؋'   },
  { code: 'IRR', name: 'Iranian Rial',                symbol: '﷼'   },
  { code: 'IQD', name: 'Iraqi Dinar',                 symbol: 'ع.د' },
  { code: 'SYP', name: 'Syrian Pound',                symbol: '£'   },
  { code: 'LBP', name: 'Lebanese Pound',              symbol: 'ل.ل.'},
  { code: 'YER', name: 'Yemeni Rial',                 symbol: '﷼'   },
  { code: 'GEL', name: 'Georgian Lari',               symbol: '₾'   },
  { code: 'AMD', name: 'Armenian Dram',               symbol: '֏'   },
  { code: 'AZN', name: 'Azerbaijani Manat',           symbol: '₼'   },
  { code: 'KZT', name: 'Kazakhstani Tenge',           symbol: '₸'   },
  { code: 'UZS', name: 'Uzbekistani Som',             symbol: 'лв'  },
  { code: 'TJS', name: 'Tajikistani Somoni',          symbol: 'SM'  },
  { code: 'TMT', name: 'Turkmenistani Manat',         symbol: 'T'   },
  { code: 'KGS', name: 'Kyrgyzstani Som',             symbol: 'лв'  },
  { code: 'MOP', name: 'Macanese Pataca',             symbol: 'P'   },
  { code: 'BWP', name: 'Botswanan Pula',              symbol: 'P'   },
  { code: 'NAD', name: 'Namibian Dollar',             symbol: '$'   },
  { code: 'ZMW', name: 'Zambian Kwacha',              symbol: 'ZK'  },
  { code: 'MWK', name: 'Malawian Kwacha',             symbol: 'MK'  },
  { code: 'MZN', name: 'Mozambican Metical',          symbol: 'MT'  },
  { code: 'AOA', name: 'Angolan Kwanza',              symbol: 'Kz'  },
  { code: 'XOF', name: 'West African CFA Franc',      symbol: 'Fr'  },
  { code: 'XAF', name: 'Central African CFA Franc',   symbol: 'Fr'  },
  { code: 'GNF', name: 'Guinean Franc',               symbol: 'Fr'  },
  { code: 'RWF', name: 'Rwandan Franc',               symbol: 'Fr'  },
  { code: 'BIF', name: 'Burundian Franc',             symbol: 'Fr'  },
  { code: 'DJF', name: 'Djiboutian Franc',            symbol: 'Fr'  },
  { code: 'KMF', name: 'Comorian Franc',              symbol: 'Fr'  },
  { code: 'SOS', name: 'Somali Shilling',             symbol: 'Sh'  },
  { code: 'ERN', name: 'Eritrean Nakfa',              symbol: 'Nfk' },
  { code: 'SDG', name: 'Sudanese Pound',              symbol: '£'   },
  { code: 'LYD', name: 'Libyan Dinar',                symbol: 'LD'  },
  { code: 'DZD', name: 'Algerian Dinar',              symbol: 'دج'  },
  { code: 'MRO', name: 'Mauritanian Ouguiya',         symbol: 'UM'  },
  { code: 'CVE', name: 'Cape Verdean Escudo',         symbol: '$'   },
  { code: 'STN', name: 'São Tomé Dobra',              symbol: 'Db'  },
  { code: 'SZL', name: 'Swazi Lilangeni',             symbol: 'L'   },
  { code: 'LSL', name: 'Lesotho Loti',                symbol: 'L'   },
  { code: 'SCR', name: 'Seychellois Rupee',           symbol: '₨'   },
  { code: 'MUR', name: 'Mauritian Rupee',             symbol: '₨'   },
  { code: 'MVR', name: 'Maldivian Rufiyaa',           symbol: 'Rf'  },
  { code: 'HTG', name: 'Haitian Gourde',              symbol: 'G'   },
  { code: 'TTD', name: 'Trinidad & Tobago Dollar',    symbol: 'TT$' },
  { code: 'JMD', name: 'Jamaican Dollar',             symbol: 'J$'  },
  { code: 'BBD', name: 'Barbadian Dollar',            symbol: 'Bds$'},
  { code: 'XCD', name: 'East Caribbean Dollar',       symbol: '$'   },
  { code: 'BSD', name: 'Bahamian Dollar',             symbol: 'B$'  },
  { code: 'BMD', name: 'Bermudian Dollar',            symbol: '$'   },
  { code: 'KYD', name: 'Cayman Islands Dollar',       symbol: '$'   },
  { code: 'GTQ', name: 'Guatemalan Quetzal',          symbol: 'Q'   },
  { code: 'HNL', name: 'Honduran Lempira',            symbol: 'L'   },
  { code: 'NIO', name: 'Nicaraguan Córdoba',          symbol: 'C$'  },
  { code: 'CRC', name: 'Costa Rican Colón',           symbol: '₡'   },
  { code: 'PAB', name: 'Panamanian Balboa',           symbol: 'B/.' },
  { code: 'DOP', name: 'Dominican Peso',              symbol: 'RD$' },
  { code: 'CUP', name: 'Cuban Peso',                  symbol: '$'   },
  { code: 'BOB', name: 'Bolivian Boliviano',          symbol: 'Bs.' },
  { code: 'PYG', name: 'Paraguayan Guaraní',          symbol: '₲'   },
  { code: 'GYD', name: 'Guyanese Dollar',             symbol: '$'   },
  { code: 'SRD', name: 'Surinamese Dollar',           symbol: '$'   },
  { code: 'FJD', name: 'Fijian Dollar',               symbol: 'FJ$' },
  { code: 'PGK', name: 'Papua New Guinean Kina',      symbol: 'K'   },
  { code: 'WST', name: 'Samoan Tālā',                 symbol: 'WS$' },
  { code: 'TOP', name: 'Tongan Paʻanga',              symbol: 'T$'  },
  { code: 'VUV', name: 'Vanuatu Vatu',                symbol: 'Vt'  },
  { code: 'SBD', name: 'Solomon Islands Dollar',      symbol: 'SI$' },
  { code: 'MKD', name: 'Macedonian Denar',            symbol: 'ден' },
  { code: 'ALL', name: 'Albanian Lek',                symbol: 'L'   },
  { code: 'BAM', name: 'Bosnia-Herzegovina Mark',     symbol: 'KM'  },
  { code: 'MDL', name: 'Moldovan Leu',                symbol: 'lei' },
  { code: 'BYN', name: 'Belarusian Ruble',            symbol: 'Br'  },
  { code: 'LVL', name: 'Latvian Lats',                symbol: 'Ls'  },
  { code: 'LTL', name: 'Lithuanian Litas',            symbol: 'Lt'  },
  { code: 'EEK', name: 'Estonian Kroon',              symbol: 'kr'  },
]

export function getCurrency(code: string): Currency | undefined {
  return CURRENCIES.find(c => c.code === code)
}

export function getCurrencySymbol(code: string): string {
  return getCurrency(code)?.symbol ?? code
}
